project_id = "wnxqzeftghgdfcdmdlgw"

[functions.generate-social-media-content]
verify_jwt = false

[functions.process-social-post]
verify_jwt = false

[functions.generate-social-image]
verify_jwt = false

[functions.phyllo-instagram-auth]
verify_jwt = false

