project_id = "wnxqzeftghgdfcdmdlgw"

[functions.generate-social-media-content]
verify_jwt = false

[functions.process-social-post]
verify_jwt = false

[functions.generate-social-image]
verify_jwt = false

[functions.phyllo-instagram-auth]
verify_jwt = false

# Make SOP conversational assistant public for the web app
[functions.sop-conversation-chat]
verify_jwt = false

# Make goal strategy assistant public for the web app
[functions.goal-strategy-chat]
verify_jwt = false