// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnxqzeftghgdfcdmdlgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueHF6ZWZ0Z2hnZGZjZG1kbGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDY5NTMsImV4cCI6MjA2ODM4Mjk1M30.dkqJnr1YLcdlf6Jtoh2LMIq8V8D2RZyZKQMKANwzDkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});